### ISSUE TITLE
Đề xuất nhạc cho Music-Player ^^

### ISSUE THREAD

**Issue by cuikho210** [thanhthido/JS#1]
List nhạc hay quá nhưng mình muốn đề xuất thêm vài bài cũng hay lắm nè

- Vịnh Trăng Khuyết
- Tiểu Vũ
- Bên bờ hồ Baikal của Lý Duy ft Châu Thâm
- Ái Thương nhạc hot tiktok ^^
- Đều Trách Tại Em - Hồ 66

Còn nhiều bài hay lắm nhưng mà không hợp nên không nên cho vô 1 list nhạc :smile: 

Nay thấy repo mới bỗng dưng phát hiện ra ai cũng học có mỗi mình chơi :sob:

**Comment by thanhthido** [comment]
Mình bận quá, giờ mới vào thì thấy thông báo đề xuất của bạn. Cảm ơn bạn về mấy bài hát ha 😄. Chúc bạn hoàn thành đồ án suôn sẻ
